name: Update Web Content at 1 PM EST

on:
  schedule:
    # Runs daily at 1 PM EST (6 PM UTC)
    - cron: '0 20 * * *'  # UTC time

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update HTML Content
        run: |
          # Use sed to replace the placeholder text in test.html
          sed -i 's/This is before using GitHub Actions/This is after using GitHub Actions/' test.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add test.html
          git commit -m "Update content in test.html to 'This is after using GitHub Actions'"
          git push
